{**********************************************************************}
{                                                                      }
{                 This auxiliary unit was generated by                 }
{                 DevExpress Project Settings Manager.                 }
{                                                                      }
{  The dxSettings unit reflects the current project settings in        }
{  the source code of your project. Do not modify this file directly.  }
{                                                                      }
{  Use the DevExpress Project Settings dialog to configure all project }
{  settings related to DevExpress components. Select the following     }
{  item in the main menu of your RAD Studio IDE to invoke the dialog:  }
{                                                                      }
{            Project | DevExpress Settings for Your Project            }
{                                                                      }
{**********************************************************************}

unit HerdManager.dxSettings;

interface

uses
  Windows, Classes, dxCore, cxLookAndFeels, dxSkinsCore,
  dxSkinsForm, dxSkinWXI, dxSkinTheBezier, dxSkinOffice2019Colorful, dxSkinOffice2019Black,
  dxSkinOffice2019DarkGray, dxSkinOffice2019White, dxSkinBasic;

implementation

procedure LoadToRoot(ARoot: TcxRootLookAndFeel);
begin
  ARoot.Kind := lfUltraFlat;
  ARoot.NativeStyle := False;
  ARoot.ScrollbarMode := sbmDefault;
  ARoot.ScrollMode := scmDefault;
  ARoot.SkinName := 'Office2019Colorful';
  ARoot.RenderMode := rmDefault;
  ARoot.TouchMode := False;
  ARoot.FormCorners := fcDefault;
  ARoot.SkinPaletteName := 'Pine';
  ARoot.ShowFormShadow := bDefault;
  ARoot.UseSkins := True;
  ARoot.UseImageSet := imsDefault;
  ARoot.UseSkinsInPopupMenus := True;
  ARoot.UseGlobalSkin := True;
end;

procedure Load;
var
  ARoot: TcxRootLookAndFeel;
begin
  cxProjectSettingsAreOverriding := True;
  cxCanUseSkinsWithoutSkinController := True;
  ARoot := TcxRootLookAndFeel.Instance;
  ARoot.BeginUpdate;
  try
    LoadToRoot(ARoot);
  finally
    ARoot.EndUpdate;
  end;
  TdxVisualRefinements.LightStyleMode := lsmOnlyBorders;
end;

initialization
  Load;
end.